# File: Makefile
# Project "schrittmacher"
# Copyright © 2017 Andreas Fink (andreas@fink.org). All rights reserved.
# Create: Andreas Fink (andreas@fink.org)
#
#

CC=clang
CFLAGS= -D_REENTRANT=1 -DDARWIN=1 -arch x86_64 -g -O2 -DSCHRITTMACHERCLIENT_CONFIG=Release -Ischrittmacherclient/
CONFIGURATION=Release
LDFLAGS= -g
MAJORVER=2
MINORVER=0
REVISION=0

LIB=libschrittmacherclient.dylib
SLIB=libschrittmacherclient.a
PKGCONFIGFILE=schrittmacherclient.pc

MFILES = $(wildcard schrittmacherclient/*.m)
HFILES = version.h $(wildcard schrittmacherclient/*.h)
MOFILES  = $(MFILES:.m=.m.o)
OFILES = $(MOFILES)

INCLUDEDIRS = -I schrittmacherclient

DEBUG_RELEASE = -DCONFIGURATION_SCHRITTMACHERCLIENT_${CONFIGURATION}=1

${LIB}: ${OFILES}
	./make_version
	${CC} -shared -o ${LIB}  ${LDFLAGS} ${OFILES} ${LIBS} ${STATIC_LIBS}

${SLIB}: ${OFILES}
	ar rcs ${SLIB} ${OFILES}
	ranlib ${SLIB}

install: ${LIB} ${SLIB}
	-mkdir -p ${DESTDIR}/usr/local/include/schrittmacherclient
	-mkdir -p ${DESTDIR}/usr/local/lib/pkgconfig
	rm -f "${DESTDIR}/usr/local/lib/${LIB}.${MAJORVER}.${MINORVER}.${REVISION}"
	rm -f "${DESTDIR}/usr/local/lib/${LIB}.${MAJORVER}.${MINORVER}"
	rm -f "${DESTDIR}/usr/local/lib/${LIB}.${MAJORVER}"
	rm -f "${DESTDIR}/usr/local/lib/${LIB}"
	install -b -g wheel -o root -m 644 "${LIB}" "${DESTDIR}/usr/local/lib/${LIB}.${MAJORVER}.${MINORVER}.${REVISION}"
	install -b -g wheel -o root -m 644 "${SLIB}" "${DESTDIR}/usr/local/lib/${SLIB}"
	ln -s "${LIB}.${MAJORVER}.${MINORVER}.${REVISION}" "${DESTDIR}/usr/local/lib/${LIB}.${MAJORVER}.${MINORVER}"
	ln -s "${LIB}.${MAJORVER}.${MINORVER}"             "${DESTDIR}/usr/local/lib/${LIB}.${MAJORVER}"
	ln -s "${LIB}.${MAJORVER}"                         "${DESTDIR}/usr/local/lib/${LIB}"
	-install -b -g wheel -o root -m 644 ${PKGCONFIGFILE} ${DESTDIR}/usr/local/lib/pkgconfig/
	-mkdir -p ${DESTDIR}/usr/local/include/schrittmacherclient
	cp $(HFILES) ${DESTDIR}/usr/local/include/schrittmacherclient

clean:
	rm -f $(LIB) $(OFILES) ${SLIB}

.SUFFIXES: .m.o .o .m .c

%.m.o:	%.m
	${CC} -c ${CFLAGS} ${DEBUG_RELEASE} -x objective-c -fobjc-arc $<  ${DEBUG_RELEASE} ${INCLUDEDIRS} -o $@



